*   Biblioteki

In [1]:
import math
import numpy as np 
import pandas as pd
import sympy as sym #biblioteka potrzebna do pochodnej
x = sym.Symbol('x') #ustawiony symbol pochodnej

# ***Metoda bijekcji***

In [2]:

#wartosci poczatkowe algorytmu z parametrami
M = 30
delta = 10**(-6)
epsilon = 10**(-24)
a1 = -1 
b1 = 4
a2 = -3
b2 = 2
a3 = -1
b3 = 5

bisection_df = pd.DataFrame(index=range(0, M+1), columns=['M','c_1','f1(x)','c_2','f2(x)','c_3','f3(x)'])
for k in range(M+1):
  bisection_df['M'][k]=k 

def function1(x): 
  f1=sym.exp(x)-1.5-sym.atan(x) #wprowadzamy funkcję dla której chcemy wyliczyć zera
  return f1  



u = function1(a1)
v = function1(b1)
e = b1 - a1

#what if function never reaches point 0
if (np.sign(u) == np.sign(v)):
  print("Wrong range!")
else:
  for i in range(M+1):
    e = e/2
    c = a1 + e
    w = function1(c)
    bisection_df['f1(x)'][i] = w
    bisection_df['c_1'][i] = c

#if we are very close to zero we end the whole procedure
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for u in range(i, M+1):
        bisection_df['f1(x)'][u] = 0
        bisection_df['c_1'][u] = c
      break
#what if not          
    if (np.sign(u) != np.sign(v)):
      b1 = c
      v = w
    else:
      a1 = c
      u = w


def function2(x): 
  f2=x**3 + 94*x**2 - 389*x +294 #wprowadzamy funkcję dla której chcemy wyliczyć zera
  return f2 

u = function2(a2)
v = function2(b2)
e = b2 - a2

#what if function never reaches point 0
if (np.sign(u) == np.sign(v)):
  print("Wrong range!")
else:
  for i in range(M+1):
    e = e/2
    c = a2 + e
    w = function1(c)
    bisection_df['f2(x)'][i] = w
    bisection_df['c_2'][i] = c

#if we are very close to zero we end the whole procedure
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for u in range(i, M+1):
        bisection_df['f2(x)'][u] = 0
        bisection_df['c_2'][u] = c
      break
#what if not          
    if (np.sign(u) != np.sign(v)):
      b2 = c
      v = w
    else:
      a2 = c
      u = w

def function3(x): 
  f3=x**3 - 5*x**2 + 3*x -7 #wprowadzamy funkcję dla której chcemy wyliczyć zera
  return f3      

u = function3(a3)
v = function3(b3)
e = b3 - a3

#what if function never reaches point 0
if (np.sign(u) == np.sign(v)):
  print("Wrong range!")
else:
  for i in range(M+1):
    e = e/2
    c = a3 + e
    w = function1(c)
    bisection_df['f3(x)'][i] = w
    bisection_df['c_3'][i] = c

#if we are very close to zero we end the whole procedure
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for u in range(i, M+1):
        bisection_df['f3(x)'][u] = 0
        bisection_df['c_3'][u] = c
      break
#what if not          
    if (np.sign(u) != np.sign(v)):
      b3 = c
      v = w
    else:
      a3 = c
      u = w      



bisection_df

,M,c_1,f1(x),c_2,f2(x),c_3,f3(x)
0,0,1.5,1.99889534709074,-0.5,-0.429821731286560,2.0,4.78190738113656
1,1,0.25,-0.460953246439123,-1.75,-0.274575844001181,0.5,-0.314926338300678
2,2,-0.375,-0.453940050938456,-2.375,-0.234711629660860,-0.25,-0.476220553801731
3,3,-0.0625,-0.498168127190567,-2.6875,-0.217372474576243,0.125,-0.491206541479935
4,4,0.09375,-0.495191640850764,-2.84375,-0.209139221900179,0.3125,-0.436046927201175
5,5,0.171875,-0.482682542522374,-2.921875,-0.205121400558880,0.40625,-0.384704869397951
6,6,0.210938,-0.473054751751172,-2.960938,-0.203136416485749,0.453125,-0.352228810542789
7,7,0.230469,-0.467323424377252,-2.980469,-0.202149831312872,0.476562,-0.334193740360882
8,8,0.240234,-0.464219444921180,-2.990234,-0.201658007231354,0.488281,-0.324715649181201
9,9,0.245117,-0.462606778198595,-2.995117,-0.201412461354871,0.494141,-0.319860089953171
10,10,0.247559,-0.461785139745099,-2.997559,-0.201289779841286,0.49707,-0.317403012261182
11,11,0.248779,-0.461370477354711,-2.998779,-0.201228461926339,0.498535,-0.316167127816241
12,12,0.24939,-0.461162183262943,-2.99939,-0.201197808677552,0.499268,-0.315547346566987
13,13,0.249695,-0.461057795230063,-2.999695,-0.201182483480108,0.499634,-0.315236995857769
14,14,0.249847,-0.461005540934039,-2.999847,-0.201174821238097,0.499817,-0.315081705441057
15,15,0.249924,-0.460979398712029,-2.999924,-0.201170990206265,0.499908,-0.315004031462056
16,16,0.249962,-0.460966323832011,-2.999962,-0.201169074712642,0.499954,-0.314965187279256
17,17,0.249981,-0.460959785449685,-2.999981,-0.201168116971404,0.499977,-0.314945763389450
18,18,0.24999,-0.460956516022934,-2.99999,-0.201167638102179,0.499989,-0.314936050994937
19,19,0.249995,-0.460954881250661,-2.999995,-0.201167398667914,0.499994,-0.314931194685276
20,20,0.249998,-0.460954063849800,-2.999998,-0.201167278950869,0.499997,-0.314928766502344
21,21,0.249999,-0.460953655145689,-2.999999,-0.201167219092368,0.499999,-0.314927552403853
22,22,0.249999,0,-2.999999,0,0.499999,0
23,23,0.249999,0,-2.999999,0,0.499999,0
24,24,0.249999,0,-2.999999,0,0.499999,0
25,25,0.249999,0,-2.999999,0,0.499999,0
26,26,0.249999,0,-2.999999,0,0.499999,0
27,27,0.249999,0,-2.999999,0,0.499999,0
28,28,0.249999,0,-2.999999,0,0.499999,0
29,29,0.249999,0,-2.999999,0,0.499999,0
30,30,0.249999,0,-2.999999,0,0.499999,0

#  ***Metoda Newtona***

**> Szczegółowy algorytm Newtona z parametrami delta i epsilon**

In [3]:
#wartosci poczatkowe algorytmu z parametrami
M = 15
delta = 10**(-6)
epsilon = 10**(-24)



**> Określenie tablicy do zapisu wyników**

In [4]:
newton_df = pd.DataFrame(index=range(0,M+1), columns=['M','w_p1','f1(x)','w_p2','f2(x)','w_p3','f3(x)'])
for k in range(M+1):
    newton_df['M'][k]=k

* zdefiniowanie funkcji oraz jej pochodnej
1. f1(x) = e^x - 1.5 - arctg(x) dla w_p = -7
2. f2(x) = x^3 + 94x^2 - 389x +294 dla w_p = 2
3. f3(x) = x^3 - 5x^2 + 3x -7 dla w_p = 5

In [5]:
def function1(x): 
    f1=sym.exp(x)-1.5-sym.atan(x) #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f1  
dx1 = sym.diff(function1(x), x) #pochodna tej funkcji
ddx1 = sym.lambdify(x, dx1) #obliczanie pochodnej w punkcie x

w_p1 = -7.0

def function2(x): 
    f2=x**3 + 94*x**2 - 389*x +294 #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f2  
dx2 = sym.diff(function2(x), x) #pochodna tej funkcji
ddx2 = sym.lambdify(x, dx2) #obliczanie pochodnej w punkcie x

w_p2 = 4.0

def function3(x): 
    f3=x**3 - 5*x**2 + 3*x -7 #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f3  
dx3 = sym.diff(function3(x), x) #pochodna tej funkcji
ddx3 = sym.lambdify(x, dx3) #obliczanie pochodnej w punkcie x

w_p3 = 5.0

In [6]:
#algorytm

w_p1 = float(w_p1)
f1 = function1(w_p1)
for q in range(M+1):
  newton_df['f1(x)'][q]=f1
  newton_df['w_p1'][q]=w_p1
  if ddx1(w_p1)==0:
    break
  w_d1 = float(w_p1 - f1/ddx1(w_p1))
  f1 = function1(w_d1) 
  if (abs(w_d1-w_p1) < delta or abs(f1) < epsilon):
    for r in range(q, M+1):
      newton_df['f1(x)'][r]=0
      newton_df['w_p1'][r]=w_p1
    break
  w_p1 = w_d1
  
  

w_p2 = float(w_p2)
f2 = function2(w_p2)
for q in range(M+1):
  newton_df['f2(x)'][q]=f2
  newton_df['w_p2'][q]=w_p2
  if ddx2(w_p2)==0:
    break
  w_d2 = float(w_p2 - f2/ddx2(w_p2))
  f2 = function2(w_d2)
  if (abs(w_d2-w_p2) < delta or abs(f2) < epsilon):
    for r in range(q, M+1):
      newton_df['f2(x)'][r]=0
      newton_df['w_p2'][r]=w_p2
    break
  w_p2 = w_d2

w_p3 = float(w_p3)
f3 = function3(w_p3)
for q in range(M+1):
  newton_df['f3(x)'][q]=f3
  newton_df['w_p3'][q]=w_p3
  if ddx3(w_p3)==0:
    break
  w_d3 = float(w_p3 - f3/ddx1(w_p3))
  f3 = function3(w_d3)
  if (abs(w_d3-w_p3) < delta or abs(f3) < epsilon):
    for r in range(q, M+1):
      newton_df['f3(x)'][r]=0
      newton_df['w_p3'][r]=w_p3
    break
  w_p3 = w_d3 


  #wyniki
newton_df

,M,w_p1,f1(x),w_p2,f2(x),w_p3,f3(x)
0,0,-7.0,-0.0701888458437128,4.0,306.0,5.0,8.0
1,1,-10.677096,-0.0225666081098759,3.255474,58.345035,4.946082,6.519223
2,2,-13.279167,-0.00436601933391256,3.026512,5.42783,4.89971,5.29145
3,3,-14.053656,-0.000239019777052984,3.000349,0.070539,4.860284,4.280418
4,4,-14.10111,-7.99584812360976e-7,3.0,0,4.827107,3.452752
5,5,-14.10127,0,3.0,0,4.799443,2.778561
6,6,-14.10127,0,3.0,0,4.776555,2.231667
7,7,-14.10127,0,3.0,0,4.757747,1.789561
8,8,-14.10127,0,3.0,0,4.742378,1.433178
9,9,-14.10127,0,3.0,0,4.729879,1.146559
10,10,-14.10127,0,3.0,0,4.719754,0.91648
11,11,-14.10127,0,3.0,0,4.711578,0.732069
12,12,-14.10127,0,3.0,0,4.704994,0.584443
13,13,-14.10127,0,3.0,0,4.699703,0.466381
14,14,-14.10127,0,3.0,0,4.695458,0.372036
15,15,-14.10127,0,3.0,0,4.692057,0.296692

# ***Metoda siecznych***

In [7]:
M=15
delta=10**(-6)
epsilon=10**(-24)

In [8]:
sieczne_df = pd.DataFrame(index=range(0,M+1), columns=['M','a1','f1(a1)','a2','f2(a2)','a3','f3(a3)'])
for k in range(M+2):
    sieczne_df['M'][k]=k

In [9]:
def function1(x): 
    f1=sym.exp(x)-1.5-sym.atan(x) 
    return f1  
a1=-20
b1=-5
def function2(x): 
    f2=x**3 + 94*x**2 - 389*x +294 
    return f2  
a2=-5
b2=10

def function3(x): 
    f3=x**3 - 5*x**2 + 3*x -7 
    return f3  
a3=0
b3=10

In [10]:
a1=float(a1)
b1=float(b1)
y11=function1(a1)
y21=function1(b1)
for t in range(M+2):
    sieczne_df['f1(a1)'][t]=y11
    sieczne_df['a1'][t]=a1
    s=(b1-a1)/(y21-y11)
    b1=a1
    y21=y11
    a1=a1-y11*s
    y11=function1(a1)
    if abs(y11)<epsilon or abs(b1-a1)<delta:
         for i in range(t,M+2):
           sieczne_df['f1(a1)'][i]=0
           sieczne_df['a1'][i]=a1
         break


a2=float(a2)
b2=float(b2)
y12=function2(a2)
y22=function2(b2)
for t in range(M+2):
    sieczne_df['f2(a2)'][t]=y12
    sieczne_df['a2'][t]=a2
    s=(b2-a2)/(y22-y12)
    b2=a2
    y22=y12
    a2=a2-y12*s
    y12=function2(a2)
    if abs(y12)<epsilon or abs(b2-a2)<delta:
         for i in range(t,M+2):
           sieczne_df['f2(a2)'][i]=0
           sieczne_df['a2'][i]=a2
         break


a3=float(a3)
b3=float(b3)
y13=function3(a3)
y23=function3(b3)
for t in range(M+2):
    sieczne_df['f3(a3)'][t]=y13
    sieczne_df['a3'][t]=a3
    s=(b3-a3)/(y23-y13)
    b3=a3
    y23=y13
    a3=a3-y13*s
    y13=function3(a3)
    if abs(y13)<epsilon or abs(b3-a3)<delta:
         for i in range(t,M+2):
           sieczne_df['f3(a3)'][i]=0
           sieczne_df['a3'][i]=a3
         break

sieczne_df

,M,a1,f1(a1),a2,f2(a2),a3,f3(a3)
0,0,-20.0,0.0208379331341075,-5.0,4464.0,0.0,-7.0
1,1,-17.7784596189585,0.0146077101019493,-33.615385,81604.642695,0.132075,-6.688689
2,2,-12.5697186640160,-0.00858926490666878,-3.344076,2608.636196,2.969793,-15.996378
3,3,-14.4983863405382,0.00193270318519767,-2.344445,1709.766626,-1.907165,-37.844764
4,4,-14.1441235135597,0.000213756048523139,-0.443017,484.695718,6.540476,78.519632
5,5,-14.1000699063149,-6.00356708879701e-6,0.309277,182.712249,0.84023,-7.416053
6,6,-14.1012733976200,1.81356556439027e-8,0.764445,52.008936,1.332149,-9.512596
7,7,-14.1012697727399,0,0.945564,11.065608,-0.89982,-14.476401
8,8,-14.1012697727399,0,0.994514,1.089083,5.609475,29.006278
9,9,-14.1012697727399,0,0.999858,0.028125,1.267277,-9.192886
10,10,-14.1012697727399,0,1.0,0,2.312256,-14.433329
11,11,-14.1012697727399,0,1.0,0,-0.565846,-10.479622
12,12,-14.1012697727399,0,1.0,0,-8.194491,-917.58938
13,13,-14.1012697727399,0,1.0,0,-0.477714,-9.683218
14,14,-14.1012697727399,0,1.0,0,-0.395412,-9.029809
15,15,-14.1012697727399,0,1.0,0,0.741975,-7.118233

# Prezentacja rozwiązań

**Biblioteki**

In [11]:
import math
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym #biblioteka potrzebna do pochodnej
#from google.colab import files
x = sym.Symbol('x') #ustawiony symbol pochodnej

**Wartości początkowe**

In [12]:
#Przyjmujemy nastepujace wartosci poczatkowe
epsilon=10**(-24) 
delta=10**(-6)
#liczba kroków
M=30

**Przykłady funkcji:**
* f(x) = x^3 - 5x^2 + 3x - 7

In [13]:
def function(x): 
    f=x**3 - 5*x**2 + 3*x - 7 #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f  
dx = sym.diff(function(x), x) #pochodna tej funkcji
ddx = sym.lambdify(x, dx) #obliczanie pochodnej w punkcie x

#poczatek przedzialu a
a=2.5
#koniec przedzialu b
b=10
#wartosc poczatkowa w_p
w_p=5

In [14]:
#Stworzenie tablicy do rankingu zbieżności
df1 = pd.DataFrame(index=range(0,M+1), columns=['M','x-bisekcja','f(x)-bisekcja','x-Newton','f(x)-Newton','x-sieczne','f(x)-sieczne'])
for k in range(M+1):
    df1['M'][k]=k 

#ALGORYTM BIJEKCJA
a_bi = float(a)
b_bi = float(b)   
u = function(a_bi)
v = function(b_bi)
e = b_bi - a_bi
if (np.sign(u) == np.sign(v)):
        print("Wrong range!")
else: 
  for p in range(M+1):
    e = e/2
    c = a_bi + e
    w = function(c)
    df1['f(x)-bisekcja'][p] = w
    df1['x-bisekcja'][p] = c
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for l in range(p,M+1):
        df1['f(x)-bisekcja'][l]=0
        df1['x-bisekcja'][l]=c
      break
    if (np.sign(u) != np.sign(v)):
      b_bi = c
      v = w
    else:
      a_bi = c
      u = w

#ALGORYTM NEWTON   

w_p=float(w_p)
funkcja_newton = function(w_p)
for q in range(M+1):
  df1['f(x)-Newton'][q]=funkcja_newton
  df1['x-Newton'][q]=w_p
  if ddx(w_p)==0:
    break
  w_d = float(w_p - funkcja_newton/ddx(w_p))
  funkcja_newton = function(w_d)
  if abs(w_d-w_p) < delta or abs(funkcja_newton) < epsilon:
    for r in range(q, M+1):
      df1['f(x)-Newton'][r]=0
      df1['x-Newton'][r]=w_p
    break
  w_p = float(w_d) 

#ALGORYTM SIECZNYCH
y1=function(a)
y2=function(b)
for t in range(M+1):
    df1['f(x)-sieczne'][t]=y1
    df1['x-sieczne'][t]=a
    s=(b-a)/(y2-y1)
    b=a
    y2=y1
    a=a-y1*s
    y1=function(a)
    if abs(y1)<epsilon or abs(b-a)<delta:
         for i in range(t,M+1):
           df1['f(x)-sieczne'][i]=0
           df1['x-sieczne'][i]=a
         break

#wyniki
df1

     M x-bisekcja f(x)-bisekcja  x-Newton f(x)-Newton x-sieczne f(x)-sieczne
0    0       6.25     60.578125       5.0         8.0       2.5      -15.125
1    1      4.375     -5.837891  4.714286    0.793003  2.710801   -15.689644
2    2     3.4375    -15.150635  4.679089    0.011283 -3.146692   -97.105953
3    3    3.90625    -11.970551  4.678574           0  3.839592   -12.588498
4    4   4.140625     -9.311916  4.678574           0  4.880168     4.786586
5    5   4.257812     -7.681655  4.678574           0  4.593505    -1.796657
6    6   4.316406     -6.787064  4.678574           0  4.671739    -0.149128
7    7   4.345703     -6.319376  4.678574           0   4.67882     0.005404
8    8   4.360352     -6.080367  4.678574           0  4.678574            0
9    9   4.367676     -5.959564  4.678574           0  4.678574            0
10  10   4.371338     -5.898836  4.678574           0  4.678574            0
11  11   4.373169     -5.868391  4.678574           0  4.678574            0
12  12   4.374084     -5.853147  4.678574           0  4.678574            0
13  13   4.374542     -5.845521  4.678574           0  4.678574            0
14  14   4.374771     -5.841706  4.678574           0  4.678574            0
15  15   4.374886     -5.839798  4.678574           0  4.678574            0
16  16   4.374943     -5.838845  4.678574           0  4.678574            0
17  17   4.374971     -5.838368  4.678574           0  4.678574            0
18  18   4.374986     -5.838129  4.678574           0  4.678574            0
19  19   4.374993      -5.83801  4.678574           0  4.678574            0
20  20   4.374996      -5.83795  4.678574           0  4.678574            0
21  21   4.374998      -5.83792  4.678574           0  4.678574            0
22  22   4.374999             0  4.678574           0  4.678574            0
23  23   4.374999             0  4.678574           0  4.678574            0
24  24   4.374999             0  4.678574           0  4.678574            0
25  25   4.374999             0  4.678574           0  4.678574            0
26  26   4.374999             0  4.678574           0  4.678574            0
27  27   4.374999             0  4.678574           0  4.678574            0
28  28   4.374999             0  4.678574           0  4.678574            0
29  29   4.374999             0  4.678574           0  4.678574            0
30  30   4.374999             0  4.678574           0  4.678574            0

In [ ]:
x_values = np.arange(-4,7,0.001)
y_values = [x**3 - 5*x**2 + 3*x - 7 for x in x_values]

plt.figure()
fig, ax = plt.subplots()
ax.scatter(x_values, y_values, s = 1)

for k in range(30):
    if k == 29:
        ax.scatter(df1['x-bisekcja'][k], 0, s = 30, c ='red', label='x-bisekcja')
        ax.scatter(df1['x-Newton'][k], 0, s = 30, c = 'green', label='x-Newton')
        ax.scatter(df1['x-sieczne'][k], 0, s = 30, c = 'yellow', label='x-sieczne')
    else:
        ax.scatter(df1['x-bisekcja'][k], 0, s = 30, c ='red') 
        ax.scatter(df1['x-Newton'][k], 0, s = 30, c = 'green')
        ax.scatter(df1['x-sieczne'][k], 0, s = 30, c = 'yellow')

for k in np.arange(-10, 10, 0.01):
  ax.scatter(k,0, s = 0.001, c = 'black')

ax.set_xlabel('x', fontsize = 14)
ax.set_ylabel('f(x)', fontsize = 14)
plt.legend()

plt.savefig("f1(x).png")
files.download("f1(x).png") 

plt.show()

* f(x)= x - tg(x)

In [ ]:
def function(x): 
    f= x - sym.tan(x) #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f  
dx = sym.diff(function(x), x) #pochodna tej funkcji
ddx = sym.lambdify(x, dx) #obliczanie pochodnej w punkcie x

#poczatek przedzialu a
a=-1
#koniec przedzialu b
b=1.5
#wartosc poczatkowa w_p
w_p=1/2

In [ ]:
df2 = pd.DataFrame(index=range(0,M+1), columns=['M','x-bisekcja','f(x)-bisekcja','x-Newton','f(x)-Newton','x-sieczne','f(x)-sieczne'])
for k in range(M+1):
    df2['M'][k]=k 



#ALGORYTM BISEKCJA
a_bi = float(a)
b_bi = float(b)   
u = function(a_bi)
v = function(b_bi)
e = b_bi - a_bi
if (np.sign(u) == np.sign(v)):
        print("Wrong range!")
else: 
  for p in range(M+1):
    e = e/2
    c = a_bi + e
    w = function(c)
    df2['f(x)-bisekcja'][p] = w
    df2['x-bisekcja'][p] = c
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for l in range(p,M+1):
        df2['f(x)-bisekcja'][l]=0
        df2['x-bisekcja'][l]=c
      break
    if (np.sign(u) != np.sign(v)):
      b_bi = c
      v = w
    else:
      a_bi = c
      u = w

#ALGORYTM NEWTON   

w_p=float(w_p)
funkcja_newton = function(w_p)
for q in range(M+1):
  df2['f(x)-Newton'][q]=funkcja_newton
  df2['x-Newton'][q]=w_p
  if ddx(w_p)==0:
    break
  w_d = float(w_p - funkcja_newton/ddx(w_p))
  funkcja_newton = function(w_d)
  if abs(w_d-w_p) < delta or abs(funkcja_newton) < epsilon:
    for r in range(q, M+1):
      df2['f(x)-Newton'][r]=0
      df2['x-Newton'][r]=w_p
    break
  w_p = float(w_d) 

#ALGORYTM SIECZNYCH
y1=float(function(a))
y2=float(function(b))
for t in range(M+2):
    df2['f(x)-sieczne'][t]=y1
    df2['x-sieczne'][t]=a
    s=float((b-a)/(y2-y1))
    b=a
    y2=y1
    a=float(a-y1*s)
    y1=function(a)
    if abs(y1)<epsilon or abs(b-a)<delta:
         for i in range(t,M+2):
           df2['f(x)-sieczne'][i]=0
           df2['x-sieczne'][i]=a
         break

#wyniki
df2

In [ ]:
x_values = np.arange(-1,1,0.001)
y_values = [x - sym.tan(x) for x in x_values]

plt.figure()
fig, ax = plt.subplots()
ax.scatter(x_values, y_values, s = 1)

for k in range(30):
    if k == 29:
        ax.scatter(df2['x-bisekcja'][k], 0, s = 30, c ='red', label='x-bisekcja')
        ax.scatter(df2['x-Newton'][k], 0, s = 30, c = 'green', label='x-Newton')
        ax.scatter(df2['x-sieczne'][k], 0, s = 30, c = 'yellow', label='x-sieczne')
    else:
        ax.scatter(df2['x-bisekcja'][k], 0, s = 30, c ='red') 
        ax.scatter(df2['x-Newton'][k], 0, s = 30, c = 'green')
        ax.scatter(df2['x-sieczne'][k], 0, s = 30, c = 'yellow')


for k in np.arange(-10, 10, 0.01):
  ax.scatter(k,0, s = 0.001, c = 'black')

ax.set_xlabel('x', fontsize = 14)
ax.set_ylabel('f(x)', fontsize = 14)
plt.legend()

plt.savefig("f2(x).png")
files.download("f2(x).png") 

plt.show()

* f(x) = 2x^4 + 24x^3 + 61x^2 - 16x + 1

In [ ]:
def function(x): 
    f=2*x**4 + 24*x**3 + 61*x**2 - 16*x + 1 #wprowadzamy funkcję dla której chcemy wyliczyć zera
    return f  
dx = sym.diff(function(x), x) #pochodna tej funkcji
ddx = sym.lambdify(x, dx) #obliczanie pochodnej w punkcie x

#poczatek przedzialu a
a=-5
#koniec przedzialu b
b=5
#wartosc poczatkowa w_p
w_p=-5

In [ ]:
df3 = pd.DataFrame(index=range(0,M+1), columns=['M','x-bisekcja','f(x)-bisekcja','x-Newton','f(x)-Newton','x-sieczne','f(x)-sieczne'])
for k in range(M+1):
    df3['M'][k]=k 



#ALGORYTM BISEKCJA
a_bi = float(a)
b_bi = float(b)   
u = function(a_bi)
v = function(b_bi)
e = b_bi - a_bi
if (np.sign(u) == np.sign(v)):
        print("Wrong range!")
else: 
  for p in range(M+1):
    e = e/2
    c = a_bi + e
    w = function(c)
    df3['f(x)-bisekcja'][p] = w
    df3['x-bisekcja'][p] = c
    if ((abs(e) < delta) or (abs(w) < epsilon)):
      for l in range(p,M+1):
        df3['f(x)-bisekcja'][l]=0
        df3['x-bisekcja'][l]=c
      break
    if (np.sign(u) != np.sign(v)):
      b_bi = c
      v = w
    else:
      a_bi = c
      u = w

#ALGORYTM NEWTON   

w_p=float(w_p)
funkcja_newton = function(w_p)
for q in range(M+1):
  df3['f(x)-Newton'][q]=funkcja_newton
  df3['x-Newton'][q]=w_p
  if ddx(w_p)==0:
    break
  w_d = float(w_p - funkcja_newton/ddx(w_p))
  funkcja_newton = function(w_d)
  if abs(w_d-w_p) < delta or abs(funkcja_newton) < epsilon:
    for r in range(q, M+1):
      df3['f(x)-Newton'][r]=0
      df3['x-Newton'][r]=w_p
    break
  w_p = float(w_d) 

#ALGORYTM SIECZNYCH
y1=function(a)
y2=function(b)
for t in range(M+2):
    df3['f(x)-sieczne'][t]=y1
    df3['x-sieczne'][t]=a
    s=(b-a)/(y2-y1)
    b=a
    y2=y1
    a=a-y1*s
    y1=function(a)
    if abs(y1)<epsilon or abs(b-a)<delta:
         for i in range(t,M+2):
           df3['f(x)-sieczne'][i]=0
           df3['x-sieczne'][i]=a
         break


#wyniki
df3

In [ ]:
x_values = np.arange(-6,2,0.001)
y_values = [2*x**4 + 24*x**3 + 61*x**2 - 16*x + 1 for x in x_values]


plt.figure()
fig, ax = plt.subplots()
ax.scatter(x_values, y_values, s = 1)

for k in range(30):
    if k == 29:
        ax.scatter(df3['x-bisekcja'][k], 0, s = 30, c ='red', label='x-bisekcja')
        ax.scatter(df3['x-Newton'][k], 0, s = 30, c = 'green', label='x-Newton')
        ax.scatter(df3['x-sieczne'][k], 0, s = 30, c = 'yellow', label='x-sieczne')
    else:
        ax.scatter(df3['x-bisekcja'][k], 0, s = 30, c ='red') 
        ax.scatter(df3['x-Newton'][k], 0, s = 30, c = 'green')
        ax.scatter(df3['x-sieczne'][k], 0, s = 30, c = 'yellow')

for k in np.arange(-10, 10, 0.01):
  ax.scatter(k,0, s = 0.001, c = 'black')

ax.set_xlabel('x', fontsize = 14)
ax.set_ylabel('f(x)', fontsize = 14)
plt.legend()

plt.savefig("f3(x).png")
files.download("f3(x).png") 

plt.show()

**Tablica odległości**

In [ ]:
#tablica odległości
odleglosc = pd.DataFrame(index=['|B - N|', '|B - S|', '|N - S|'], columns=['|| f(x) = x^3 - 5x^2 + 3x - 7 |','| f(x)= x - tg(x) |','| f(x) = 2x^4 + 24x^3 + 61x^2 - 16x + 1 ||'])

#rozwiązania
#funkcja 1 - df1
B1 = df1[df1['f(x)-bisekcja']==0].iloc[0]['x-bisekcja']
N1 = df1[df1['f(x)-Newton']==0].iloc[0]['x-Newton']
S1 = df1[df1['f(x)-sieczne']==0].iloc[0]['x-sieczne']

#funkcja 2 - df2
B2 = df2[df2['f(x)-bisekcja']==0].iloc[0]['x-bisekcja']
N2 = df2[df2['f(x)-Newton']==0].iloc[0]['x-Newton']
S2 = df2['x-sieczne'][30]

#funkcja 3 - df3
B3 = df3[df3['f(x)-bisekcja']==0].iloc[0]['x-bisekcja']
N3 = df3[df3['f(x)-Newton']==0].iloc[0]['x-Newton']
S3 = df3[df3['f(x)-sieczne']==0].iloc[0]['x-sieczne']

#odległości
odleglosc['|| f(x) = x^3 - 5x^2 + 3x - 7 |'][0] = abs(B1-N1)
odleglosc['|| f(x) = x^3 - 5x^2 + 3x - 7 |'][1] = abs(B1-S1)
odleglosc['|| f(x) = x^3 - 5x^2 + 3x - 7 |'][2] = abs(S1-N1)

odleglosc['| f(x)= x - tg(x) |'][0] = abs(B2-N2)
odleglosc['| f(x)= x - tg(x) |'][1] = abs(B2-S2)
odleglosc['| f(x)= x - tg(x) |'][2] = abs(S2-N2)

odleglosc['| f(x) = 2x^4 + 24x^3 + 61x^2 - 16x + 1 ||'][0] = abs(B3-N3)
odleglosc['| f(x) = 2x^4 + 24x^3 + 61x^2 - 16x + 1 ||'][1] = abs(B3-S3)
odleglosc['| f(x) = 2x^4 + 24x^3 + 61x^2 - 16x + 1 ||'][2] = abs(S3-N3)

odleglosc